# Generated by Django 2.1 on 2018-11-10 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk', models.CharField(max_length=1024)),
                ('chunk_translation', models.CharField(max_length=1024)),
                ('chunk_tree_string', models.CharField(max_length=1024)),
                ('similar_cards', models.CharField(default=None, max_length=128, null=True)),
                ('question_tree_string', models.CharField(default=None, max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QandA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(default=None, max_length=1024, null=True)),
                ('answer_correct', models.BooleanField(default=None, null=True)),
                ('question', models.ForeignKey(on_delete=None, to='lang_app.Card')),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.CharField(max_length=1024, unique=True)),
                ('sentence_tree_string', models.CharField(default=None, max_length=1024)),
                ('uncommon_words_score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(max_length=1024)),
                ('next_session', models.ForeignKey(default=None, null=True, on_delete=None, to='lang_app.Session')),
                ('user', models.ForeignKey(on_delete=None, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_size', models.IntegerField(default=3)),
                ('current_session', models.OneToOneField(blank=True, default=None, null=True, on_delete=None, to='lang_app.Session')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='qanda',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lang_app.Session'),
        ),
        migrations.AddField(
            model_name='card',
            name='sentence',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='lang_app.Sentence'),
        ),
    ]
