# Generated by Django 2.1 on 2018-11-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lang_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstate',
            name='current_policy_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
