# Generated by Django 2.1 on 2018-10-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lang_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='uncommon_words_score',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
