# Generated by Django 2.0.7 on 2018-07-25 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lang_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentence',
            old_name='content',
            new_name='sentence',
        ),
    ]
