# Generated by Django 2.1 on 2018-11-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lang_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='initial_cards',
            new_name='all_correct',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='test_cards',
            new_name='all_incorrect',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='training_cards',
            new_name='initial_questions',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mode',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='test_questions',
            field=models.CharField(default=None, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='training_questions',
            field=models.CharField(default=None, max_length=1024, null=True),
        ),
    ]
