# Generated by Django 2.1 on 2018-11-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lang_app', '0002_auto_20181126_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstate',
            name='current_policy_id',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
