# Generated by Django 2.1 on 2018-11-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lang_app', '0003_auto_20181127_0929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qanda',
            options={'verbose_name': 'QandA', 'verbose_name_plural': 'QandAs'},
        ),
        migrations.RemoveField(
            model_name='userstate',
            name='block_size',
        ),
        migrations.AddField(
            model_name='session',
            name='block_size',
            field=models.IntegerField(default=3),
        ),
    ]
