# Generated by Django 2.1 on 2018-11-10 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lang_app', '0003_auto_20181109_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qanda',
            name='answer',
            field=models.CharField(default=None, max_length=1024),
        ),
        migrations.AlterField(
            model_name='session',
            name='next_session',
            field=models.ForeignKey(default=None, null=True, on_delete=None, to='lang_app.Session'),
        ),
        migrations.AlterField(
            model_name='userstate',
            name='current_session',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='lang_app.Session'),
        ),
    ]
