# Generated by Django 2.1 on 2018-11-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lang_app', '0006_userstate_split'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstate',
            name='split',
        ),
        migrations.AddField(
            model_name='session',
            name='split',
            field=models.FloatField(blank=True, default=0.5, null=True),
        ),
    ]
